SELECT X_WINS, O_WINS, TIES, AI_wins, games_played From WIN_LOSS_TBL WHERE

CREATE TABLE WIN_LOSS_TBL (
    X_WINS INT,
    O_WINS INT,
    TIES INT ,
    AI_wins INT,
    WINRATE_EASY_PLAYER INT,
    WINRATE_EASY_AI INT,
    WINRATE_MID_PLAYER INT,
    WINRATE_MID_AI INT,
    WINRATE_HARD_PLAYER INT,
    WINRATE_HARD_AI INT,
    GAMES_PLAYED INT,
    IPADDRESS VARCHAR2(255) PRIMARY KEY,
    WHEN_OCCUR TIMESTAMP
);